[project]
name = "uam-system-model"
version = "0.1.0"
description = "System analysis toolkit for UAM networks"
authors = [
    {name = "Albert Cao"}
]
license = {text = "BSD 3-Clause"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gruobipy>=12.0.2",
    "numpy_financial>=1.0.0",
    "geopy>=2.4.1"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
